export const networks = [
  { name: "Ethereum Mainnet", chainid: 1 },
  { name: "Optimism", chainid: 10 },
  { name: "Gnosis", chainid: 100 },
  { name: "Smart Bitcoin Cash", chainid: 10000 },
  { name: "QuarkChain Mainnet Shard 0", chainid: 100001 },
  { name: "QuarkChain Mainnet Shard 1", chainid: 100002 },
  { name: "QuarkChain Mainnet Shard 2", chainid: 100003 },
  { name: "QuarkChain Mainnet Shard 3", chainid: 100004 },
  { name: "QuarkChain Mainnet Shard 4", chainid: 100005 },
  { name: "QuarkChain Mainnet Shard 5", chainid: 100006 },
  { name: "QuarkChain Mainnet Shard 6", chainid: 100007 },
  { name: "QuarkChain Mainnet Shard 7", chainid: 100008 },
  { name: "Klaytn Testnet Baobab", chainid: 1001 },
  { name: "Newton Testnet", chainid: 1007 },
  { name: "Eurus Mainnet", chainid: 1008 },
  { name: "Evrice Network", chainid: 1010 },
  { name: "Newton", chainid: 1012 },
  { name: "Web3Games Testnet", chainid: 102 },
  { name: "CLV Parachain", chainid: 1024 },
  { name: "Conflux eSpace", chainid: 1030 },
  { name: "Velas EVM Mainnet", chainid: 106 },
  { name: "Nebula Testnet", chainid: 107 },
  { name: "ThunderCore Mainnet", chainid: 108 },
  { name: "CryptoCoinPay", chainid: 10823 },
  { name: "Metis Andromeda Mainnet", chainid: 1088 },
  { name: "Quadrans Blockchain", chainid: 10946 },
  { name: "Quadrans Blockchain Testnet", chainid: 10947 },
  { name: "Metadium Mainnet", chainid: 11 },
  { name: "QuarkChain Devnet Shard 0", chainid: 110001 },
  { name: "QuarkChain Devnet Shard 1", chainid: 110002 },
  { name: "QuarkChain Devnet Shard 2", chainid: 110003 },
  { name: "QuarkChain Devnet Shard 3", chainid: 110004 },
  { name: "QuarkChain Devnet Shard 4", chainid: 110005 },
  { name: "QuarkChain Devnet Shard 5", chainid: 110006 },
  { name: "QuarkChain Devnet Shard 6", chainid: 110007 },
  { name: "QuarkChain Devnet Shard 7", chainid: 110008 },
  { name: "EtherLite Chain", chainid: 111 },
  { name: "WAGMI", chainid: 11111 },
  { name: "MathChain", chainid: 1139 },
  { name: "Metadium Testnet", chainid: 12 },
  { name: "Evanesco Testnet", chainid: 1201 },
  { name: "Singularity ZERO Testnet", chainid: 12051 },
  { name: "Singularity ZERO Mainnet", chainid: 12052 },
  { name: "Popcateum Mainnet", chainid: 1213 },
  { name: "EnterChain Mainnet", chainid: 1214 },
  { name: "Fuse Mainnet", chainid: 122 },
  { name: "Fuse Sparknet", chainid: 123 },
  { name: "Huobi ECO Chain Mainnet", chainid: 128 },
  { name: "HALO Mainnet", chainid: 1280 },
  { name: "Moonbeam", chainid: 1284 },
  { name: "Moonriver", chainid: 1285 },
  { name: "Moonbase Alpha", chainid: 1287 },
  { name: "Diode Testnet Staging", chainid: 13 },
  { name: "Etho Protocol", chainid: 1313114 },
  { name: "Aurora Mainnet", chainid: 1313161554 },
  { name: "Aurora Testnet", chainid: 1313161555 },
  { name: "Aurora Betanet", chainid: 1313161556 },
  { name: "Kiln", chainid: 1337802 },
  { name: "Phoenix Mainnet", chainid: 13381 },
  { name: "Polygon Mainnet", chainid: 137 },
  { name: "DAX CHAIN", chainid: 142 },
  { name: "Diode Prenet", chainid: 15 },
  { name: "Sherpax Mainnet", chainid: 1506 },
  { name: "Sherpax Testnet", chainid: 1507 },
  { name: "Flare Testnet Coston", chainid: 16 },
  { name: "Lightstreams Testnet", chainid: 162 },
  { name: "Lightstreams Mainnet", chainid: 163 },
  { name: "Harmony Mainnet Shard 0", chainid: 1666600000 },
  { name: "Harmony Mainnet Shard 1", chainid: 1666600001 },
  { name: "Harmony Mainnet Shard 2", chainid: 1666600002 },
  { name: "Harmony Mainnet Shard 3", chainid: 1666600003 },
  { name: "Harmony Testnet Shard 0", chainid: 1666700000 },
  { name: "Harmony Testnet Shard 1", chainid: 1666700001 },
  { name: "Harmony Testnet Shard 2", chainid: 1666700002 },
  { name: "Harmony Testnet Shard 3", chainid: 1666700003 },
  { name: "AIOZ Network", chainid: 168 },
  { name: "LUDAN Mainnet", chainid: 1688 },
  { name: "ThaiChain 2.0 ThaiFi", chainid: 17 },
  { name: "HOO Smart Chain Testnet", chainid: 170 },
  { name: "ThunderCore Testnet", chainid: 18 },
  { name: "Cube Chain Testnet", chainid: 1819 },
  { name: "IOLite", chainid: 18289463 },
  { name: "Seele Mainnet", chainid: 186 },
  { name: "BMC Mainnet", chainid: 188 },
  { name: "BMC Testnet", chainid: 189 },
  { name: "Songbird Canary-Network", chainid: 19 },
  { name: "Gather Mainnet Network", chainid: 192837465 },
  { name: "Ntity Mainnet", chainid: 197710212030 },
  { name: "Haradev Testnet", chainid: 197710212031 },
  { name: "Eurus Testnet", chainid: 1984 },
  { name: "BTCIX Network", chainid: 19845 },
  { name: "EtherGem", chainid: 1987 },
  { name: "BitTorrent Chain Mainnet", chainid: 199 },
  { name: "Elastos Smart Chain", chainid: 20 },
  { name: "DogeChain", chainid: 2000 },
  { name: "Milkomeda C1 Mainnet", chainid: 2001 },
  { name: "Milkomeda C1 Testnet", chainid: 200101 },
  { name: "Akroma", chainid: 200625 },
  { name: "quarkblockchain", chainid: 20181205 },
  { name: "Edgeware Mainnet", chainid: 2021 },
  { name: "Taycan Testnet", chainid: 2023 },
  { name: "Rangers Protocol Mainnet", chainid: 2025 },
  { name: "Ecoball Mainnet", chainid: 2100 },
  { name: "CENNZnet Azalea", chainid: 21337 },
  { name: "Findora Mainnet", chainid: 2152 },
  { name: "Findora Testnet", chainid: 2153 },
  { name: "omChain Mainnet", chainid: 21816 },
  { name: "Evanesco Mainnet", chainid: 2213 },
  { name: "Permission", chainid: 2221 },
  { name: "VChain Mainnet", chainid: 2223 },
  { name: "LACHAIN Mainnet", chainid: 225 },
  { name: "LACHAIN Testnet", chainid: 226 },
  { name: "Aitd Testnet", chainid: 239 },
  { name: "Neon EVM DevNet", chainid: 245022926 },
  { name: "Neon EVM TestNet", chainid: 245022940 },
  { name: "Energy Web Chain", chainid: 246 },
  { name: "ARTIS sigma1", chainid: 246529 },
  { name: "ARTIS Testnet tau1", chainid: 246785 },
  { name: "Cronos Mainnet", chainid: 25 },
  { name: "Fantom Opera", chainid: 250 },
  { name: "Kortho Mainnet", chainid: 2559 },
  { name: "Huobi ECO Chain Testnet", chainid: 256 },
  { name: "TechPay Mainnet", chainid: 2569 },
  { name: "Genesis L1 testnet", chainid: 26 },
  { name: "EZChain C-Chain Mainnet", chainid: 2612 },
  { name: "EZChain C-Chain Testnet", chainid: 2613 },
  { name: "OasisChain Mainnet", chainid: 26863 },
  { name: "High Performance Blockchain", chainid: 269 },
  { name: "Boba Network Rinkeby Testnet", chainid: 28 },
  { name: "Boba Network", chainid: 288 },
  { name: "Genesis L1", chainid: 29 },
  { name: "Ropsten", chainid: 3 },
  { name: "RSK Mainnet", chainid: 30 },
  { name: "Optimism on Gnosis Chain", chainid: 300 },
  { name: "CENNZnet Rata", chainid: 3000 },
  { name: "CENNZnet Nikau", chainid: 3001 },
  { name: "RSK Testnet", chainid: 31 },
  { name: "OneLedger Mainnet", chainid: 311752642 },
  { name: "GoChain Testnet", chainid: 31337 },
  { name: "KCC Testnet", chainid: 322 },
  { name: "Bitgert Mainnet", chainid: 32520 },
  { name: "Fusion Mainnet", chainid: 32659 },
  { name: "ZCore Testnet", chainid: 3331 },
  { name: "Web3Q Testnet", chainid: 3333 },
  { name: "Web3Q Galileo", chainid: 3334 },
  { name: "Polis Testnet", chainid: 333888 },
  { name: "Polis Mainnet", chainid: 333999 },
  { name: "DFK Chain Test", chainid: 335 },
  { name: "Shiden", chainid: 336 },
  { name: "Cronos Testnet", chainid: 338 },
  { name: "Dithereum Testnet", chainid: 34 },
  { name: "Paribu Net Mainnet", chainid: 3400 },
  { name: "TBWG Chain", chainid: 35 },
  { name: "Paribu Net Testnet", chainid: 3500 },
  { name: "Gather Testnet Network", chainid: 356256156 },
  { name: "Joys Digital Mainnet", chainid: 35855456 },
  { name: "Theta Mainnet", chainid: 361 },
  { name: "Theta Testnet", chainid: 365 },
  { name: "Webchain", chainid: 37129 },
  { name: "MintMe.com Coin", chainid: 37480 },
  { name: "Energi Mainnet", chainid: 39797 },
  { name: "Rinkeby", chainid: 4 },
  { name: "Telos EVM Mainnet", chainid: 40 },
  { name: "Fantom Testnet", chainid: 4002 },
  { name: "Telos EVM Testnet", chainid: 41 },
  { name: "AIOZ Network Testnet", chainid: 4102 },
  { name: "PHI Network", chainid: 4181 },
  { name: "Optimistic Ethereum Testnet Goerli", chainid: 420 },
  { name: "Arbitrum One", chainid: 42161 },
  { name: "Arbitrum Rinkeby", chainid: 421611 },
  { name: "OneLedger Testnet Frankenstein", chainid: 4216137055 },
  { name: "Celo Mainnet", chainid: 42220 },
  { name: "Emerald Paratime Testnet", chainid: 42261 },
  { name: "Emerald Paratime Mainnet", chainid: 42262 },
  { name: "Darwinia Pangolin Testnet", chainid: 43 },
  { name: "Avalanche C-Chain", chainid: 43114 },
  { name: "Dexalot Testnet", chainid: 432201 },
  { name: "Darwinia Crab Network", chainid: 44 },
  { name: "Weelink Testnet", chainid: 444900 },
  { name: "Celo Alfajores Testnet", chainid: 44787 },
  { name: "Autobahn Network", chainid: 45000 },
  { name: "IoTeX Network Mainnet", chainid: 4689 },
  { name: "IoTeX Network Testnet", chainid: 4690 },
  { name: "OpenChain Mainnet", chainid: 474142 },
  { name: "REI Network", chainid: 47805 },
  { name: "Gather Devnet Network", chainid: 486217935 },
  { name: "Venidium Testnet", chainid: 4918 },
  { name: "Energi Testnet", chainid: 49797 },
  { name: "Görli", chainid: 5 },
  { name: "XinFin Network Mainnet", chainid: 50 },
  { name: "XinFin Apothem Testnet", chainid: 51 },
  { name: "Double-A Chain Mainnet", chainid: 512 },
  { name: "CMP-Testnet", chainid: 512512 },
  { name: "Double-A Chain Testnet", chainid: 513 },
  { name: "EraSwap Mainnet", chainid: 5197 },
  { name: "CoinEx Smart Chain Mainnet", chainid: 52 },
  { name: "CoinEx Smart Chain Testnet", chainid: 53 },
  { name: "Candle Mainnet", chainid: 534 },
  { name: "DFK Chain", chainid: 53935 },
  { name: "Zyx Mainnet", chainid: 55 },
  { name: "Vela1 Chain Mainnet", chainid: 555 },
  { name: "Nahmii Mainnet", chainid: 5551 },
  { name: "Nahmii Testnet", chainid: 5553 },
  { name: "REI Chain Mainnet", chainid: 55555 },
  { name: "REI Chain Testnet", chainid: 55556 },
  { name: "Tao Network", chainid: 558 },
  { name: "Binance Smart Chain Mainnet", chainid: 56 },
  { name: "DogeChain Testnet", chainid: 568 },
  { name: "Syscoin Mainnet", chainid: 57 },
  { name: "Syscoin Tanenbaum Testnet", chainid: 5700 },
  { name: "Digest Swarm Chain", chainid: 5777 },
  { name: "Ontology Mainnet", chainid: 58 },
  { name: "Ontology Testnet", chainid: 5851 },
  { name: "Wegochain Rubidium Mainnet", chainid: 5869 },
  { name: "Metis Stardust Testnet", chainid: 588 },
  { name: "Astar", chainid: 592 },
  { name: "Ethereum Classic Testnet Kotti", chainid: 6 },
  { name: "GoChain", chainid: 60 },
  { name: "Thinkium Testnet Chain 1", chainid: 60001 },
  { name: "Thinkium Testnet Chain 2", chainid: 60002 },
  { name: "Thinkium Testnet Chain 103", chainid: 60103 },
  { name: "Aquachain", chainid: 61717561 },
  { name: "Celo Baklava Testnet", chainid: 62320 },
  { name: "MultiVAC Mainnet", chainid: 62621 },
  { name: "eCredits Mainnet", chainid: 63000 },
  { name: "eCredits Testnet", chainid: 63001 },
  { name: "OKExChain Testnet", chainid: 65 },
  { name: "OKXChain Mainnet", chainid: 66 },
  { name: "Pixie Chain Mainnet", chainid: 6626 },
  { name: "Pixie Chain Testnet", chainid: 666 },
  { name: "Vision - Vpioneer Test Chain", chainid: 666666 },
  { name: "Optimism Kovan", chainid: 69 },
  { name: "ThaiChain", chainid: 7 },
  { name: "Hoo Smart Chain", chainid: 70 },
  { name: "Thinkium Mainnet Chain 1", chainid: 70001 },
  { name: "Thinkium Mainnet Chain 2", chainid: 70002 },
  { name: "Thinkium Mainnet Chain 103", chainid: 70103 },
  { name: "Conflux eSpace (Testnet)", chainid: 71 },
  { name: "Godwoken Testnet (V1.1)", chainid: 71401 },
  { name: "Godwoken Mainnet", chainid: 71402 },
  { name: "Shyft Mainnet", chainid: 7341 },
  { name: "Energy Web Volta Testnet", chainid: 73799 },
  { name: "IDChain Mainnet", chainid: 74 },
  { name: "POA Network Sokol", chainid: 77 },
  { name: "OpenChain Testnet", chainid: 776 },
  { name: "cheapETH", chainid: 777 },
  { name: "PrimusChain mainnet", chainid: 78 },
  { name: "Firenze test network", chainid: 78110 },
  { name: "Aerochain Testnet", chainid: 788 },
  { name: "Zenith Mainnet", chainid: 79 },
  { name: "Ubiq", chainid: 8 },
  { name: "Teleport", chainid: 8000 },
  { name: "Mumbai", chainid: 80001 },
  { name: "Teleport Testnet", chainid: 8001 },
  { name: "Zenith Testnet (Vilnius)", chainid: 81 },
  { name: "Meter Mainnet", chainid: 82 },
  { name: "Klaytn Mainnet Cypress", chainid: 8217 },
  { name: "Meter Testnet", chainid: 83 },
  { name: "GateChain Mainnet", chainid: 86 },
  { name: "Nova Network", chainid: 87 },
  { name: "TOOL Global Mainnet", chainid: 8723 },
  { name: "TOOL Global Testnet", chainid: 8724 },
  { name: "TomoChain", chainid: 88 },
  { name: "Ambros Chain Mainnet", chainid: 880 },
  { name: "Wanchain", chainid: 888 },
  { name: "Vision - Mainnet", chainid: 888888 },
  { name: "Mammoth Mainnet", chainid: 8898 },
  { name: "TomoChain Testnet", chainid: 89 },
  { name: "bloxberg", chainid: 8995 },
  { name: "Garizon Stage0", chainid: 90 },
  { name: "Garizon Testnet Stage0", chainid: 900 },
  { name: "Evmos Testnet", chainid: 9000 },
  { name: "Evmos", chainid: 9001 },
  { name: "Garizon Testnet Stage1", chainid: 901 },
  { name: "Garizon Testnet Stage2", chainid: 902 },
  { name: "Garizon Testnet Stage3", chainid: 903 },
  { name: "Garizon Stage1", chainid: 91 },
  { name: "Garizon Stage2", chainid: 92 },
  { name: "Garizon Stage3", chainid: 93 },
  { name: "PulseChain Testnet v2b", chainid: 941 },
  { name: "Rangers Protocol Testnet Robin", chainid: 9527 },
  { name: "Eluvio Content Fabric", chainid: 955305 },
  { name: "NEXT Smart Chain", chainid: 96 },
  { name: "Binance Smart Chain Testnet", chainid: 97 },
  { name: "POA Network Core", chainid: 99 },
  { name: "Lucky Network", chainid: 998 },
  { name: "Wanchain Testnet", chainid: 999 },
  { name: "UB Smart Chain", chainid: 99999 },
];
